/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WolfartRouteImport } from './routes/wolfart'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BeschwerdenRouteImport } from './routes/beschwerden'
import { Route as BehandlungenRouteImport } from './routes/behandlungen'
import { Route as AktuellesRouteImport } from './routes/aktuelles'
import { Route as AerzteRouteImport } from './routes/aerzte'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeschwerdenIndexRouteImport } from './routes/beschwerden.index'
import { Route as AerzteIndexRouteImport } from './routes/aerzte.index'
import { Route as BeschwerdenSlugRouteImport } from './routes/beschwerden.$slug'
import { Route as AerzteSlugRouteImport } from './routes/aerzte.$slug'

const WolfartRoute = WolfartRouteImport.update({
  id: '/wolfart',
  path: '/wolfart',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BeschwerdenRoute = BeschwerdenRouteImport.update({
  id: '/beschwerden',
  path: '/beschwerden',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandlungenRoute = BehandlungenRouteImport.update({
  id: '/behandlungen',
  path: '/behandlungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesRoute = AktuellesRouteImport.update({
  id: '/aktuelles',
  path: '/aktuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const AerzteRoute = AerzteRouteImport.update({
  id: '/aerzte',
  path: '/aerzte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeschwerdenIndexRoute = BeschwerdenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BeschwerdenRoute,
} as any)
const AerzteIndexRoute = AerzteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AerzteRoute,
} as any)
const BeschwerdenSlugRoute = BeschwerdenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BeschwerdenRoute,
} as any)
const AerzteSlugRoute = AerzteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AerzteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aerzte': typeof AerzteRouteWithChildren
  '/aktuelles': typeof AktuellesRoute
  '/behandlungen': typeof BehandlungenRoute
  '/beschwerden': typeof BeschwerdenRouteWithChildren
  '/faq': typeof FaqRoute
  '/karriere': typeof KarriereRoute
  '/wolfart': typeof WolfartRoute
  '/aerzte/$slug': typeof AerzteSlugRoute
  '/beschwerden/$slug': typeof BeschwerdenSlugRoute
  '/aerzte/': typeof AerzteIndexRoute
  '/beschwerden/': typeof BeschwerdenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/behandlungen': typeof BehandlungenRoute
  '/faq': typeof FaqRoute
  '/karriere': typeof KarriereRoute
  '/wolfart': typeof WolfartRoute
  '/aerzte/$slug': typeof AerzteSlugRoute
  '/beschwerden/$slug': typeof BeschwerdenSlugRoute
  '/aerzte': typeof AerzteIndexRoute
  '/beschwerden': typeof BeschwerdenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aerzte': typeof AerzteRouteWithChildren
  '/aktuelles': typeof AktuellesRoute
  '/behandlungen': typeof BehandlungenRoute
  '/beschwerden': typeof BeschwerdenRouteWithChildren
  '/faq': typeof FaqRoute
  '/karriere': typeof KarriereRoute
  '/wolfart': typeof WolfartRoute
  '/aerzte/$slug': typeof AerzteSlugRoute
  '/beschwerden/$slug': typeof BeschwerdenSlugRoute
  '/aerzte/': typeof AerzteIndexRoute
  '/beschwerden/': typeof BeschwerdenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aerzte'
    | '/aktuelles'
    | '/behandlungen'
    | '/beschwerden'
    | '/faq'
    | '/karriere'
    | '/wolfart'
    | '/aerzte/$slug'
    | '/beschwerden/$slug'
    | '/aerzte/'
    | '/beschwerden/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktuelles'
    | '/behandlungen'
    | '/faq'
    | '/karriere'
    | '/wolfart'
    | '/aerzte/$slug'
    | '/beschwerden/$slug'
    | '/aerzte'
    | '/beschwerden'
  id:
    | '__root__'
    | '/'
    | '/aerzte'
    | '/aktuelles'
    | '/behandlungen'
    | '/beschwerden'
    | '/faq'
    | '/karriere'
    | '/wolfart'
    | '/aerzte/$slug'
    | '/beschwerden/$slug'
    | '/aerzte/'
    | '/beschwerden/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AerzteRoute: typeof AerzteRouteWithChildren
  AktuellesRoute: typeof AktuellesRoute
  BehandlungenRoute: typeof BehandlungenRoute
  BeschwerdenRoute: typeof BeschwerdenRouteWithChildren
  FaqRoute: typeof FaqRoute
  KarriereRoute: typeof KarriereRoute
  WolfartRoute: typeof WolfartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wolfart': {
      id: '/wolfart'
      path: '/wolfart'
      fullPath: '/wolfart'
      preLoaderRoute: typeof WolfartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beschwerden': {
      id: '/beschwerden'
      path: '/beschwerden'
      fullPath: '/beschwerden'
      preLoaderRoute: typeof BeschwerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandlungen': {
      id: '/behandlungen'
      path: '/behandlungen'
      fullPath: '/behandlungen'
      preLoaderRoute: typeof BehandlungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles': {
      id: '/aktuelles'
      path: '/aktuelles'
      fullPath: '/aktuelles'
      preLoaderRoute: typeof AktuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aerzte': {
      id: '/aerzte'
      path: '/aerzte'
      fullPath: '/aerzte'
      preLoaderRoute: typeof AerzteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beschwerden/': {
      id: '/beschwerden/'
      path: '/'
      fullPath: '/beschwerden/'
      preLoaderRoute: typeof BeschwerdenIndexRouteImport
      parentRoute: typeof BeschwerdenRoute
    }
    '/aerzte/': {
      id: '/aerzte/'
      path: '/'
      fullPath: '/aerzte/'
      preLoaderRoute: typeof AerzteIndexRouteImport
      parentRoute: typeof AerzteRoute
    }
    '/beschwerden/$slug': {
      id: '/beschwerden/$slug'
      path: '/$slug'
      fullPath: '/beschwerden/$slug'
      preLoaderRoute: typeof BeschwerdenSlugRouteImport
      parentRoute: typeof BeschwerdenRoute
    }
    '/aerzte/$slug': {
      id: '/aerzte/$slug'
      path: '/$slug'
      fullPath: '/aerzte/$slug'
      preLoaderRoute: typeof AerzteSlugRouteImport
      parentRoute: typeof AerzteRoute
    }
  }
}

interface AerzteRouteChildren {
  AerzteSlugRoute: typeof AerzteSlugRoute
  AerzteIndexRoute: typeof AerzteIndexRoute
}

const AerzteRouteChildren: AerzteRouteChildren = {
  AerzteSlugRoute: AerzteSlugRoute,
  AerzteIndexRoute: AerzteIndexRoute,
}

const AerzteRouteWithChildren =
  AerzteRoute._addFileChildren(AerzteRouteChildren)

interface BeschwerdenRouteChildren {
  BeschwerdenSlugRoute: typeof BeschwerdenSlugRoute
  BeschwerdenIndexRoute: typeof BeschwerdenIndexRoute
}

const BeschwerdenRouteChildren: BeschwerdenRouteChildren = {
  BeschwerdenSlugRoute: BeschwerdenSlugRoute,
  BeschwerdenIndexRoute: BeschwerdenIndexRoute,
}

const BeschwerdenRouteWithChildren = BeschwerdenRoute._addFileChildren(
  BeschwerdenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AerzteRoute: AerzteRouteWithChildren,
  AktuellesRoute: AktuellesRoute,
  BehandlungenRoute: BehandlungenRoute,
  BeschwerdenRoute: BeschwerdenRouteWithChildren,
  FaqRoute: FaqRoute,
  KarriereRoute: KarriereRoute,
  WolfartRoute: WolfartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
