/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AerzteRouteImport } from './routes/aerzte'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeschwerdenRouteImport } from './routes/beschwerden'
import { Route as BehandlungenRouteImport } from './routes/behandlungen'
import { Route as AktuellesRouteImport } from './routes/aktuelles'
import { Route as AerzteIndexRouteImport } from './routes/aerzte.index'
import { Route as AerzteSlugRouteImport } from './routes/aerzte.$slug'

const AerzteRoute = AerzteRouteImport.update({
  id: '/aerzte',
  path: '/aerzte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeschwerdenRoute = BeschwerdenRouteImport.update({
  id: '/beschwerden',
  path: '/beschwerden',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandlungenRoute = BehandlungenRouteImport.update({
  id: '/behandlungen',
  path: '/behandlungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesRoute = AktuellesRouteImport.update({
  id: '/aktuelles',
  path: '/aktuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const AerzteIndexRoute = AerzteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AerzteRoute,
} as any)
const AerzteSlugRoute = AerzteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AerzteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beschwerden': typeof BeschwerdenRoute
  '/behandlungen': typeof BehandlungenRoute
  '/aktuelles': typeof AktuellesRoute
  '/aerzte': typeof AerzteRouteWithChildren
  '/aerzte/$slug': typeof AerzteSlugRoute
  '/aerzte/': typeof AerzteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beschwerden': typeof BeschwerdenRoute
  '/behandlungen': typeof BehandlungenRoute
  '/aktuelles': typeof AktuellesRoute
  '/aerzte/$slug': typeof AerzteSlugRoute
  '/aerzte': typeof AerzteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beschwerden': typeof BeschwerdenRoute
  '/behandlungen': typeof BehandlungenRoute
  '/aktuelles': typeof AktuellesRoute
  '/aerzte': typeof AerzteRouteWithChildren
  '/aerzte/$slug': typeof AerzteSlugRoute
  '/aerzte/': typeof AerzteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/beschwerden' | '/behandlungen' | '/aktuelles' | '/aerzte' | '/aerzte/$slug' | '/aerzte/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/beschwerden' | '/behandlungen' | '/aktuelles' | '/aerzte/$slug' | '/aerzte'
  id: '__root__' | '/' | '/beschwerden' | '/behandlungen' | '/aktuelles' | '/aerzte' | '/aerzte/$slug' | '/aerzte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeschwerdenRoute: typeof BeschwerdenRoute
  BehandlungenRoute: typeof BehandlungenRoute
  AktuellesRoute: typeof AktuellesRoute
  AerzteRoute: typeof AerzteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aerzte': {
      id: '/aerzte'
      path: '/aerzte'
      fullPath: '/aerzte'
      preLoaderRoute: typeof AerzteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beschwerden': {
      id: '/beschwerden'
      path: '/beschwerden'
      fullPath: '/beschwerden'
      preLoaderRoute: typeof BeschwerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandlungen': {
      id: '/behandlungen'
      path: '/behandlungen'
      fullPath: '/behandlungen'
      preLoaderRoute: typeof BehandlungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles': {
      id: '/aktuelles'
      path: '/aktuelles'
      fullPath: '/aktuelles'
      preLoaderRoute: typeof AktuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aerzte/': {
      id: '/aerzte/'
      path: '/'
      fullPath: '/aerzte/'
      preLoaderRoute: typeof AerzteIndexRouteImport
      parentRoute: typeof AerzteRoute
    }
    '/aerzte/$slug': {
      id: '/aerzte/$slug'
      path: '/$slug'
      fullPath: '/aerzte/$slug'
      preLoaderRoute: typeof AerzteSlugRouteImport
      parentRoute: typeof AerzteRoute
    }
  }
}

interface AerzteRouteChildren {
  AerzteSlugRoute: typeof AerzteSlugRoute
  AerzteIndexRoute: typeof AerzteIndexRoute
}

const AerzteRouteChildren: AerzteRouteChildren = {
  AerzteSlugRoute: AerzteSlugRoute,
  AerzteIndexRoute: AerzteIndexRoute,
}

const AerzteRouteWithChildren =
  AerzteRoute._addFileChildren(AerzteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeschwerdenRoute: BeschwerdenRoute,
  BehandlungenRoute: BehandlungenRoute,
  AktuellesRoute: AktuellesRoute,
  AerzteRoute: AerzteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
